#!/usr/bin/env python3
"""
Build the bitmap font headers used by the firmware.

Renders a TrueType font with FreeType into the 4-bit-per-pixel glyph format
the LilyGo EPD47 driver expects (GFXfont / GFXglyph / UnicodeInterval), and
zlib-compresses each glyph so the large sizes stay small in flash.

    pip install freetype-py
    python tools/make_fonts.py

Edit FONTS below to add or change sizes, then re-run. Output goes to
src/fonts/, one header per font.
"""
import os
import zlib
import freetype

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
TTF_DIR = os.path.join(ROOT, "assets", "fonts")
OUT_DIR = os.path.join(ROOT, "src", "fonts")

# (symbol name, ttf file, size in points at the panel's ~150 dpi)
FONTS = [
    ("Sans9",       "OpenSans-Regular.ttf", 9),
    ("Sans11",      "OpenSans-Regular.ttf", 11),
    ("Sans13",      "OpenSans-Regular.ttf", 13),
    ("SansBold11",  "OpenSans-Bold.ttf",    11),
    ("SansBold14",  "OpenSans-Bold.ttf",    14),
    ("SansBold17",  "OpenSans-Bold.ttf",    17),
    ("SansBold20",  "OpenSans-Bold.ttf",    20),
    ("SansBold48",  "OpenSans-Bold.ttf",    48),
]

# Printable ASCII plus the degree sign. Ranges must be ascending and disjoint.
RANGES = [(0x20, 0x7E), (0xB0, 0xB0)]

DPI = 150


def px(v26_6, up=False):
    """FreeType 26.6 fixed point -> whole pixels."""
    q, r = divmod(v26_6, 64)
    return q + (1 if up and r else 0)


def pack_4bpp(bitmap):
    """8-bit coverage rows -> 4-bit pixels, two per byte, left pixel in the low nibble."""
    out = bytearray()
    w, h, pitch = bitmap.width, bitmap.rows, bitmap.pitch
    buf = bitmap.buffer
    for row in range(h):
        line = buf[row * pitch:row * pitch + w]
        for i in range(0, w, 2):
            lo = line[i] >> 4
            hi = (line[i + 1] >> 4) if i + 1 < w else 0
            out.append(lo | (hi << 4))
    return bytes(out)


def build(name, ttf, size):
    face = freetype.Face(os.path.join(TTF_DIR, ttf))
    face.set_char_size(size * 64, size * 64, DPI, DPI)

    blob = bytearray()
    glyphs = []
    for first, last in RANGES:
        for cp in range(first, last + 1):
            face.load_char(chr(cp), freetype.FT_LOAD_RENDER)
            g = face.glyph
            data = zlib.compress(pack_4bpp(g.bitmap), 9)
            glyphs.append((g.bitmap.width, g.bitmap.rows, px(g.advance.x),
                           g.bitmap_left, g.bitmap_top, len(data), len(blob), cp))
            blob += data

    m = face.size
    lines = [
        "// Generated by tools/make_fonts.py from " + ttf + " (SIL Open Font License, see assets/fonts/OFL.txt).",
        "// Do not edit by hand.",
        "#pragma once",
        '#include "epd_driver.h"',
        "",
        f"static const uint8_t {name}_bitmaps[{len(blob)}] = {{",
    ]
    for i in range(0, len(blob), 20):
        lines.append("  " + ",".join(f"0x{b:02X}" for b in blob[i:i + 20]) + ",")
    lines.append("};")
    lines.append(f"static const GFXglyph {name}_glyphs[] = {{")
    for w, h, adv, left, top, csize, off, cp in glyphs:
        label = "deg" if cp == 0xB0 else ("bslash" if cp == 0x5C else chr(cp))
        lines.append(f"  {{{w},{h},{adv},{left},{top},{csize},{off}}}, // {label}")
    lines.append("};")
    lines.append(f"static const UnicodeInterval {name}_ranges[] = {{")
    index = 0
    for first, last in RANGES:
        lines.append(f"  {{0x{first:X}, 0x{last:X}, {index}}},")
        index += last - first + 1
    lines.append("};")
    lines.append(f"static const GFXfont {name} = {{")
    lines.append(f"  (uint8_t *){name}_bitmaps, (GFXglyph *){name}_glyphs, (UnicodeInterval *){name}_ranges,")
    lines.append(f"  {len(RANGES)}, true, {px(m.height, up=True)}, {px(m.ascender, up=True)}, {px(m.descender)}")
    lines.append("};")

    path = os.path.join(OUT_DIR, name + ".h")
    with open(path, "w", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print(f"{name:12s} {len(blob):7d} bytes  -> {os.path.relpath(path, ROOT)}")


if __name__ == "__main__":
    os.makedirs(OUT_DIR, exist_ok=True)
    for spec in FONTS:
        build(*spec)
